# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'AthelasProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AthelasProject
  pod 'SwiftyJSON', '3.1.4'
  pod 'Charts', '3.0.1'

  target 'AthelasProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AthelasProject-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AthelasProject-tvOS

  target 'AthelasProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
